### PR TITLE
fix CI

### PR DESCRIPTION
**Pull request by whereismyjetpack**

### CODE REVIEW

**Comment by ajkiessl** [comment]
@whereismyjetpack I guess this repo needs moved to psu-libraries for that context.

**Comment by whereismyjetpack** [comment]
ah, we can make one in stewardship -- thanks for the heads up. I think eventually we should move the repo? whadda think?

**Comment by ajkiessl** [comment]
Yeah, we can move the repo.  Can that wait until after Thanksgiving?

**Comment by jrpatterson** [comment]
@ajkiessl   I don't see why not unless something breaks before than that you want to run against CI before pushing out.

**Comment by ajkiessl** [comment]
@whereismyjetpack There appears to be some authentication issue with harbor at the publish step, other than that I think this is ready to go.

**Comment by whereismyjetpack** [comment]
@ajkiessl you should be unblocked. I've updated the harbor password in circle.

**Pull request merged**
