### PR TITLE
updates dissertation language

### LINKED ISSUE #764: Update language in dissertation section
From Grad School:

> In ETD Admin, throughout the Dissertation section, there are several instances where the word "thesis" is used. Please change these instances to "dissertation".  For example, in the "Format Review is Submitted" status box, the subheading says "Thesis drafts to be reviewed" (change this to dissertation).  Doctoral students = Dissertation, Masters students = Thesis

We should review the whole application for any more issues like this.

### PR DESCRIPTION
**Pull request by Smullz622**
Fixes #764 - adds logic to use the correct language with the correct graduate degree type

`title_for` and `description_for` are used for all filters in each instance, but we only want to change it for the grad school instance for dissertation degree types on the filters that have the word thesis/dissertation. The logic feels a little clunky, but the only alternative I could think if was to add `thesis_description` to the translation for all of the filters which would be redundant/unnecessary for a lot of them. I considered using interpolation, but since capitalization varies by filter (Dissertation vs dissertation), it felt like the logic to handle that wouldn't be an improvement.

### CODE REVIEW

**Comment by jlandiseigsti** [comment]
Yeah, I see what you mean wrt capitalization being an issue with interpolation. I played around with it a bit, since I generally like interpolation, but didn't come up with a solution I liked...there's not a way, as far I could tell, to just have the string in the yaml file automatically be sentence case. Plus there's plural vs. singular potentially screwing things up as well. I think your solution makes sense.

**Review by ajkiessl — CHANGES_REQUESTED** [review]
Yeah I think this is probably the best way to handle this.  Could we add some unit tests to test the logic in these methods?

**Review by ajkiessl — COMMENTED** [review]
I think you can use `#capitalize` to properly capitalize a sentence.  So maybe we _could_ do interpolation here, but use `#capitalize` on the whole string returned by `I18n`?

I'm just not too sure how I feel about this logic: `&& !thesis_title.match?(/Translation missing/)`.

**Comment by jlandiseigsti** [comment]
> I think you can use `#capitalize` to properly capitalize a sentence. So maybe we _could_ do interpolation here, but use `#capitalize` on the whole string returned by `I18n`?
> 
> I'm just not too sure how I feel about this logic: `&& !thesis_title.match?(/Translation missing/)`.

There is also the complication of irregular pluralization going on: 'Thesis' turning into 'theses', which would add another step to interpolation. But I do agree that matching on the 'Translation missing' string feels brittle – it would break if I18n changed the error message wording.

**Comment by ajkiessl** [comment]
> There is also the complication of irregular pluralization going on: 'Thesis' turning into 'theses', which would add another step to interpolation. But I do agree that matching on the 'Translation missing' string feels brittle – it would break if I18n changed the error message wording.

Oh right.  What if we change `Thesis drafts to be reviewed` to `Draft theses to be reviewed`.  Then they'd all be plural.

**Comment by Smullz622** [comment]
That would work; I'll try interpolation with `#capitalize `

**Review by jlandiseigsti — APPROVED** [review]
Looks good!

**Review by ajkiessl — APPROVED** [review]

**Pull request merged**
