### PR TITLE
Adds "7 Days" warning to email sent to core committee to request review

### LINKED ISSUE #485: Add "7 Days" warning to email sent to core committee to request review
There should be some logic to differentiate between core committee members/advisors/program heads.  Only the core committee should see this wording and it should say something like: "You have seven days to complete your review".

### PR DESCRIPTION
**Pull request by banukutlu**
Closes #485

Screen Shot 2022-06-02 at 2 49 23 PM

Screen Shot 2022-06-02 at 3 25 46 PM

### CODE REVIEW

**Comment by ajkiessl** [comment]
@banukutlu This looks good.  After reviewing this, I realized we need the 7 days message added to the special_committee_review_request email 🤦‍♂️.  

Special committee members will always be the core committee, so we don't have to concern ourselves with the core committee logic.  However, the special_committee_review_request is sent twice.  First as the initial request, and then a second time as a reminder.  So we'd only want the 7 days message on the first sending.  If the approval_started_at timestamp is blank, then we know this is the initial email.  Could you add something in that mailer like this?:

`@note = @committee_member.approval_started_at.blank? ? "You have seven days to complete your review." : ""`

And then display that in the email?

**Comment by ajkiessl** [comment]
@banukutlu This looks good.  After reviewing this, I realized we need the 7 days message added to the special_committee_review_request email 🤦‍♂️.  

Special committee members will always be the core committee, so we don't have to concern ourselves with the core committee logic.  However, the special_committee_review_request is sent twice.  First as the initial request, and then a second time as a reminder.  So we'd only want the 7 days message on the first sending.  If the approval_started_at timestamp is blank, then we know this is the initial email.  Could you add something in that mailer like this?:

`@note = @committee_member.approval_started_at.blank? ? "You have seven days to complete your review." : ""`

And then display that in the email?

**Comment by banukutlu** [comment]
> @banukutlu This looks good. After reviewing this, I realized we need the 7 days message added to the special_committee_review_request email 🤦‍♂️.
> 
> Special committee members will always be the core committee, so we don't have to concern ourselves with the core committee logic. However, the special_committee_review_request is sent twice. First as the initial request, and then a second time as a reminder. So we'd only want the 7 days message on the first sending. If the approval_started_at timestamp is blank, then we know this is the initial email. Could you add something in that mailer like this?:
> 
> `@note = @committee_member.approval_started_at.blank? ? "You have seven days to complete your review." : ""`
> 
> And then display that in the email?

ohh oki sure, I will change the logic :) 👍🏻

**Comment by ajkiessl** [comment]
@banukutlu Looks good!  As I mentioned during pairing, this just needs the core committee stuff from your previous commit added back in and then I think we'll be ready to go.

**Review by ajkiessl — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
