### PR TITLE
Fixes issue 575

### LINKED ISSUE #575: Special Members help text
We do not get names or emails for Special Members from LionPATH.  We are only made aware that a record exists, so we leave an empty field for authors to fill out when they get to the committee page.  The empty box sometimes confuses users, so we may want to add help text somewhere to mention the student needs to fill in their Special Member.

### PR DESCRIPTION
**Pull request by khsarvar**
Added description for thesis Committee Member add page about Special Members. "If your committee requires a Special Member, you will see an empty box below for that member's information. Please fill in this data before submitting the form." Fixes #575

### CODE REVIEW

**Review by karthikreddy-02 — DISMISSED** [review]
LGTM

**Review by Smullz622 — DISMISSED** [review]
LGTM

**Review by ajkiessl — CHANGES_REQUESTED** [review]
Just one change request.

**Review by ajkiessl — APPROVED** [review]
LGTM

**Pull request merged**
